[maps]
automation_test_track = "/levels/automation_test_track/info.json"
cliff = "/levels/cliff/info.json"
derby = "/levels/derby/info.json"
driver_training = "/levels/driver_training/info.json"
east_coast_usa = "/levels/east_coast_usa/info.json"
gridmap_v2 = "/levels/gridmap_v2/info.json"
hirochi_raceway = "/levels/hirochi_raceway/info.json"
industrial = "/levels/industrial/info.json"
italy = "/levels/italy/info.json"
johnson_valley = "/levels/johnson_valley/info.json"
jungle_rock_island = "/levels/jungle_rock_island/info.json"
small_island = "/levels/small_island/info.json"
smallgrid = "/levels/smallgrid/info.json"
utah = "/levels/utah/info.json"
west_coast_usa = "/levels/west_coast_usa/info.json"
